name: Nexus bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      token: ${{ secrets.TOKEN }}
      username: ${{ secrets.USERNAME }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: python main.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TOKEN }}
        BOT_USERNAME: ${{ secrets.USERNAME }}
