name: Nexus bot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TOKEN }}
      BOT_USERNAME: ${{ secrets.USERNAME }}
      GT_TOKEN: ${{ secrets.GT_TOKEN }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Git Operations
      run: |
        git config --global user.email "rodrigo2005contente@gmail.com"
        git config --global user.name "NotZeetaa"

    - name: Run Python Script
      run: python main.py
